version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "8000:5432"   # External 8000 â†’ Internal 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demon-test-db